asyn:
  min_received_num: 1
  min_received_rate: -1
  time_budget: 3
  use: true
backend: torch
criterion:
  type: CrossEntropyLoss
data:
  args: []
  cSBM_phi:
  - 0.5
  - 0.5
  - 0.5
  drop_last: false
  loader: ''
  num_steps: 30
  num_workers: 0
  pre_transform: []
  root: data/
  save_data: false
  shuffle: true
  sizes:
  - 10
  - 5
  splits:
  - 0.6
  - 0.2
  - 0.2
  splitter: ''
  splitter_args: []
  subsample: 0.05
  target_transform: []
  transform:
  - - ToTensor
    - {}
  - - Normalize
    - mean:
      - 0.1307
      std:
      - 0.3081
  type: femnist
  walk_length: 2
dataloader:
  batch_size: 32
device: -1
distribute:
  use: false
early_stop:
  delta: 0
  improve_indicator_mode: best
  patience: 3
eval:
  best_res_update_round_wise_key: val_loss
  freq: 10
  metrics:
  - acc
  - correct
  monitoring: []
  report:
  - weighted_avg
  - avg
  - fairness
  - raw
  split:
  - test
  - val
expname: Ditto_convnet2_on_femnist_lr0.05_lstep3_
expname_tag: ''
federate:
  client_num: 200
  data_weighted_aggr: false
  ignore_weight: false
  join_in_info: []
  make_global_eval: false
  method: Ditto
  mode: standalone
  online_aggr: false
  restore_from: ''
  sample_client_num: 32
  save_to: ''
  share_local_model: false
  total_round_num: 1000
  unseen_clients_rate: 0.2
  use_ss: false
fedopt:
  use: false
fedprox:
  use: false
fedsageplus:
  a: 1.0
  b: 1.0
  c: 1.0
  fedgen_epoch: 200
  gen_hidden: 128
  hide_portion: 0.5
  loc_epoch: 1
  num_pred: 5
finetune:
  before_eval: false
  local_update_steps: 5
  optimizer:
    lr: 0.01
gcflplus:
  EPS_1: 0.05
  EPS_2: 0.1
  seq_length: 5
  standardize: false
grad:
  grad_clip: 5
hpo:
  fedex:
    cutoff: 0
    diff: false
    flatten_ss: true
    gamma: 0
    sched: auto
    ss: ''
    use: false
  init_cand_num: 16
  larger_better: false
  metric: client_summarized_weighted_avg.test_loss
  scheduler: sha
  sha:
    budgets: []
    elim_rate: 3
  working_folder: hpo
model:
  dropout: 0
  embed_size: 8
  graph_pooling: mean
  hidden: 2048
  in_channels: 0
  layer: 2
  model_num_per_trainer: 1
  num_item: 0
  num_user: 0
  out_channels: 62
  task: node
  type: convnet2
  use_bias: true
nbafl:
  use: false
outdir: exp_pfl_bench/Ditto_convnet2_on_femnist_lr0.05_lstep3_/sub_exp_20220523003100
personalization:
  K: 5
  beta: 1
  local_param: []
  local_update_steps: 1
  lr: 0.01
  regular_weight: 0.2
  share_non_trainable_para: false
regularizer:
  mu: 0
  type: ''
seed: 1
sgdmf:
  use: false
train:
  batch_or_epoch: epoch
  local_update_steps: 3
  optimizer:
    lr: 0.05
    momentum: 0
    type: SGD
    weight_decay: 0
use_gpu: true
verbose: 1
vertical:
  use: false
wandb:
  name_project: pFL-bench
  name_user: jakob-eigenmann
  online_track: true
  use: true
